@rem %1 - msvc version - 2017/2019

@set MSVC_ROOT_PATH_NO_DRIVE=Program Files (x86)\Microsoft Visual Studio

@set COMMON7_VSDEVCMD=Common7\Tools\VsDevCmd.bat
@set COMMUNITY_COMMON7_VSDEVCMD=Community\Common7\Tools\VsDevCmd.bat


:TEST_COMMON7_ON_C
@if not exist "C:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%" goto TEST_COMMUNITY_ON_C
@set VSDEVCMD_BAT=C:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMUNITY_ON_C
@if not exist "C:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%" goto TEST_COMMON7_ON_D
@set VSDEVCMD_BAT=C:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMON7_ON_D
@if not exist "D:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%" goto TEST_COMMUNITY_ON_D
@set VSDEVCMD_BAT=D:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMUNITY_ON_D
@if not exist "D:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%" goto TEST_COMMON7_ON_E
@set VSDEVCMD_BAT=D:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMON7_ON_E
@if not exist "E:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%" goto TEST_COMMUNITY_ON_E
@set VSDEVCMD_BAT=E:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMUNITY_ON_E
@if not exist "E:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%" goto TEST_COMMON7_ON_F
@set VSDEVCMD_BAT=E:\%MSVC_ROOT_PATH_NO_DRIVE%\%1\%COMMUNITY_COMMON7_VSDEVCMD%
@exit /b 0


:TEST_COMMON7_ON_F
@exit /b 1

